### ISSUE TITLE
start_tcp_server: no acceptor

### ISSUE THREAD

**Issue by gmolittieri** [StanHutcheon/SiriAuth#1]
After installing everything and following all the directions I can find, I cannot get past:

[root@ip-XXX-XXX-XX-XXX SiriAuth]# sudo ruby ./start.rb
/usr/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:572:in `start_tcp_server': no acceptor (RuntimeError)
    from /usr/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:572:in`start_server'
    from ./siriAuth.rb:286:in `initialize'
    from /usr/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`call'
    from /usr/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /usr/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from ./siriAuth.rb:285:in `initialize'
    from ./start.rb:5:in`new'
    from ./start.rb:5

I have the 4S auth info but I left it out for obvious reasons. This is on CentOS Linux

I have tried /usr/sbin/lsof -Pnl +M -i4 | grep LISTEN | grep 443 but nothing is running!

**Comment by StanHutcheon** [comment]
You need to make sure nothing is running on ports 53 and 443

**Comment by alnandr** [comment]
Is there any way we can make SiriAuth listen with another port other than 443 using a --port option?

**Comment by StanHutcheon** [comment]
i'm going to incorporate custom IP address and port next push
